<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $candle_category_id = DB::table('categories')->insertGetId([
            'name' => 'Candle',
            'slug' => 'candle',
            'description' => 'This is the candle category',
            'image' => 'uploads/category/first.png',
            'meta_title' => 'Candle',
            'meta_keyword' => 'This is the candle category',
            'meta_description' => 'This is the candle category',
            'status' => 0,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);

        $honey_category_id = DB::table('categories')->insertGetId([
            'name' => 'Honey',
            'slug' => 'honey',
            'description' => 'This is the honey category',
            'image' => 'uploads/category/second.png',
            'meta_title' => 'Honey',
            'meta_keyword' => 'This is the honey category',
            'meta_description' => 'This is the honey category',
            'status' => 0,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);

        $soap_category_id = DB::table('categories')->insertGetId([
            'name' => 'Soap',
            'slug' => 'soap',
            'description' => 'This is the soap category',
            'image' => 'uploads/category/third.png',
            'meta_title' => 'Soap',
            'meta_keyword' => 'This is the soap category',
            'meta_description' => 'This is the soap category',
            'status' => 0,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);

        DB::table('products')->insert([
            [
                'category_id' => $candle_category_id,
                'name' => 'Beeswax Candle',
                'slug' => 'beeswax-candle',
                'small_description' => 'This is a candle made out of beeswax.',
                'description' => 'This is a candle made out of beeswax.',
                'original_price' => 13.99,
                'selling_price' => 11.99,
                'quantity' => 10,
                'trending' => 0,
                'status' => 0,
                'meta_title' => 'Beeswax Candle',
                'meta_keyword' => 'This is a candle made out of beeswax.',
                'meta_description' => 'This is a candle made out of beeswax.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => $candle_category_id,
                'name' => 'Beeswax Jar Candle',
                'slug' => 'beeswax-jar-candle',
                'small_description' => 'This is a candle made out of beeswax and put into a jar.',
                'description' => 'This is a candle made out of beeswax and put into a jar.',
                'original_price' => 24.99,
                'selling_price' => 20,
                'quantity' => 2,
                'trending' => 0,
                'status' => 0,
                'meta_title' => 'Beeswax Jar Candle',
                'meta_keyword' => 'This is a candle made out of beeswax and put into a jar.',
                'meta_description' => 'This is a candle made out of beeswax and put into a jar.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => $candle_category_id,
                'name' => 'Beeswax Pillar Candle',
                'slug' => 'beeswax-pillar-candle',
                'small_description' => 'This is a candle made out of beeswax.',
                'description' => 'PURE AND HEALTY- We use only clean 100% Pure Beeswax and Organic cotton wick. It is totally natural. It does not contain paraffin, toxic substances, dyes, perfumes, or any additives',
                'original_price' => 17.50,
                'selling_price' => 17,
                'quantity' => 2,
                'trending' => 0,
                'status' => 0,
                'meta_title' => 'Beeswax Pillar Candle',
                'meta_keyword' => 'This is a candle made out of beeswax.',
                'meta_description' => 'This is a candle made out of beeswax and put into a jar.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => $candle_category_id,
                'name' => 'Bluecorn Beeswax Candle',
                'slug' => 'bluecorn-beeswax-candle',
                'small_description' => 'This is a candle made out of beeswax.',
                'description' => 'Bluecorn Beeswax 100% Raw Beeswax Candle in 50% Recycled Glass (2¾-Inch Dia. x 3¾-Inch Tall) 35 Hour Burn Time',
                'original_price' => 22.99,
                'selling_price' => 21.80,
                'quantity' => 2,
                'trending' => 0,
                'status' => 0,
                'meta_title' => 'Bluecorn Beeswax Candle',
                'meta_keyword' => 'This is a candle made out of beeswax and put into a jar.',
                'meta_description' => 'This is a candle made out of beeswax and put into a jar.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => $candle_category_id,
                'name' => 'Ivory Beeswax Candle',
                'slug' => 'ivory-beeswax-candle',
                'small_description' => 'This is a candle made out of beeswax.',
                'description' => 'Toxin Free - Here at Alternative Imagination we are dedicated to creating products that are good for people as well as the planet! Every Beeswax Pillar Candle is made with a flat, natural cotton wick that features a paper thread for structure and contains no heavy metals or toxic chemicals.',
                'original_price' => 31.99,
                'selling_price' => 28.75,
                'quantity' => 2,
                'trending' => 0,
                'status' => 0,
                'meta_title' => 'Ivory Beeswax Candle',
                'meta_keyword' => 'This is a candle made out of beeswax and put into a jar.',
                'meta_description' => 'This is a candle made out of beeswax and put into a jar.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => $honey_category_id,
                'name' => 'Mint Honey',
                'slug' => 'mint-honey',
                'small_description' => 'This is mint honey.',
                'description' => 'This is mint honey.',
                'original_price' => 19.99,
                'selling_price' => 16.99,
                'quantity' => 5,
                'trending' => 1,
                'status' => 0,
                'meta_title' => 'Mint Honey',
                'meta_keyword' => 'This is mint honey.',
                'meta_description' => 'This is mint honey.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => $honey_category_id,
                'name' => 'Greek Honey',
                'slug' => 'greek-honey',
                'small_description' => 'This is greek honey.',
                'description' => '100% pure, unheated, unfiltered Greek honey, single sourced from one local beekeeper.',
                'original_price' => 20.99,
                'selling_price' => 14.99,
                'quantity' => 10,
                'trending' => 1,
                'status' => 0,
                'meta_title' => 'Greek Honey',
                'meta_keyword' => 'This is greek honey.',
                'meta_description' => 'This is greek honey.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => $honey_category_id,
                'name' => 'Clover Honey',
                'slug' => 'clover-honey',
                'small_description' => 'This is clover honey.',
                'description' => ' Happy Belly Clover Honey, 16 Ounce This product was previously a Solimo product. Now it’s part of the Happy Belly brand, the product is exactly the same size and quality.',
                'original_price' => 31.19,
                'selling_price' => 28.50,
                'quantity' => 5,
                'trending' => 1,
                'status' => 0,
                'meta_title' => 'Clover Honey',
                'meta_keyword' => 'This is clover honey.',
                'meta_description' => 'This is clover honey.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => $honey_category_id,
                'name' => 'Thyme Honey 1kg',
                'slug' => 'thyme-honey',
                'small_description' => 'This is thyme honey.',
                'description' => 'Thyme honey has a soft creamy taste with a gentle herbal hint of thyme, subtle and slightly savoury, ideal for all the family due to its balanced and pleasing flavour.',
                'original_price' => 25.95,
                'selling_price' => 23.50,
                'quantity' => 5,
                'trending' => 1,
                'status' => 0,
                'meta_title' => 'Thyme Honey',
                'meta_keyword' => 'This is thyme honey.',
                'meta_description' => 'This is thyme honey.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
